Repository prgrms-web-devcourse/Team_i6_comepet_BE, pull requests merged in 2021-12, with the labels that each got.

#20 [CP-16]feat: 엔티티 클래스 생성
  src/main/java/com/pet/domains/animal/AnimalKind.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/domain/MissingPostImage.java
  src/main/java/com/pet/domains/post/domain/SexType.java
  src/main/java/com/pet/domains/post/domain/Status.java
  src/main/java/com/pet/domains/tag/PostTag.java
  src/main/java/com/pet/domains/tag/Tag.java
Labels: feat, merge needed

#22 [CP-17] feat: 엔티티 클래스 생성2
  src/main/java/com/pet/domains/bookmark/domain/MissingPostBookmark.java
  src/main/java/com/pet/domains/bookmark/domain/ShelterPostBookmark.java
  src/main/java/com/pet/domains/post/domain/NeuteredType.java
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/post/domain/ShelterSexType.java
  src/main/java/com/pet/domains/statistics/domain/PostStatistics.java
Labels: feat, merge needed

#24 [CP-23] chore: 소나 클라우드 세팅
  .github/workflows/sonar.yml
  build.gradle
Labels: chore

#21 [CP-15] feat: 엔티티 클래스 생성1
  src/main/java/com/pet/common/config/JpaAuditingConfig.java
  src/main/java/com/pet/domains/BaseEntity.java
  src/main/java/com/pet/domains/DeletableEntity.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/domain/Notification.java
  src/main/java/com/pet/domains/account/repository/AccountRepository.java
  src/main/java/com/pet/domains/area/domain/City.java
  src/main/java/com/pet/domains/area/domain/InterestArea.java
  src/main/java/com/pet/domains/area/domain/Town.java
  src/main/java/com/pet/domains/comment/domain/Comment.java
Labels: feat, merge needed

#28 [CP-26] chore: jacoco 연동 해제
  build.gradle
Labels: chore, review needed

#31 [CP-27] 엔티티 연관관계 설정 2
  src/main/java/com/pet/domains/bookmark/domain/MissingPostBookmark.java
  src/main/java/com/pet/domains/bookmark/domain/ShelterPostBookmark.java
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/statistics/domain/PostStatistics.java
Labels: feat, merge needed

#32 [CP-29] 엔티티 연관관계 추가3
  src/main/java/com/pet/domains/account/domain/Notification.java
  src/main/java/com/pet/domains/area/domain/InterestArea.java
  src/main/java/com/pet/domains/area/domain/Town.java
  src/main/java/com/pet/domains/comment/domain/Comment.java
  src/main/resources/application.yaml
Labels: feat, merge needed

#35 [CP-34 ] 소나 클라우드 자코코 연동해제2
  .github/workflows/sonar.yml
  build.gradle
Labels: chore, review needed

#37 [CP-36] chore: s3 Code Deploy 트리거 생성
  .github/workflows/deploy.yml
Labels: chore

#39 [CP-38] s3 jar zip 업로드 테스트 pr
  .github/workflows/gradle.yml
  src/main/java/com/pet/Application.java
Labels: chore, review needed

#41 [CP-40] S3 Code Deploy 문서 수정
  .github/workflows/deploy.yml
  src/main/java/com/pet/Application.java
Labels: bug

#44 [CP-43] chore: CD 파일 설정
  appspec.yml
  deploy.sh
Labels: chore

#45 [CP-42] chore: github action code deploy 트리거 생성
  .github/workflows/deploy.yml
Labels: chore

#47 [CP-46] fix: 개행 추가
  .github/workflows/deploy.yml
Labels: bug

#49 [CP-48] feat: 서버 확인용 health check api 추가
  src/main/java/com/pet/domains/account/controller/AccountController.java
Labels: feat

#51 [CP-50] fix: location key 수정
  .github/workflows/deploy.yml
Labels: bug

#52 [CP-50] fix: location key 수정2
  .github/workflows/deploy.yml
Labels: bug

#53 [CP-50] fix: 파일 오타 및 경로 수정
  .github/workflows/deploy.yml
  appspec.yml
Labels: bug

#54 [CP-50] code deploy 패턴 수정
  .github/workflows/deploy.yml
  appspec.yml
Labels: bug

#56 [CP-50 ] 배포 마지막 수정
  .github/workflows/deploy.yml
  appspec.yml
  deploy.sh
  src/main/java/com/pet/domains/HealthCheckController.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
Labels: bug

#59 [CP-57] chore: CI/CD 통합
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
Labels: chore, review needed

#62 Revert "[CP-57] chore: CI/CD 통합"
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
Labels: revert

#68 [CP-67] chore: apache commons lang 패키지로 수정
  build.gradle
Labels: chore

#69 [CP-66] feat: date LocalDateTime으로 수정
  src/main/java/com/pet/domains/statistics/domain/PostStatistics.java
Labels: feat, review needed

#70 [CP-61] feat: api response 포멧 생성
  src/main/java/com/pet/common/response/ApiResponse.java
  src/test/java/com/pet/common/response/ApiResponseTest.java
Labels: feat

#71 [CP-60] feat: Image 테이블 변경에 따른 엔티티 수정
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/image/domain/Image.java
  src/main/java/com/pet/domains/post/domain/MissingPostImage.java
Labels: refactoring, answer needed

#78 [CP-73] feat: 지역, 회원 mocking 데이터 추가
  build.gradle
  src/main/java/com/pet/common/config/WebMvcConfig.java
  src/main/java/com/pet/common/exception/ExceptionHandler.java
  src/main/java/com/pet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/pet/common/interceptor/JwtAuthenticationInterceptor.java
  src/main/java/com/pet/common/jwt/JwtMockToken.java
  src/main/java/com/pet/common/response/ErrorResponse.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/dto/request/AccountCreateParam.java
  src/main/java/com/pet/domains/account/dto/request/AccountEmailParam.java
  src/main/java/com/pet/domains/account/dto/request/AccountLonginParam.java
  src/main/java/com/pet/domains/account/dto/request/AccountPasswordParam.java
  src/main/java/com/pet/domains/account/dto/request/AccountUpdateParam.java
  src/main/java/com/pet/domains/account/dto/request/SampleRequest.java
  src/main/java/com/pet/domains/account/dto/response/AccountAreaReadResults.java
  src/main/java/com/pet/domains/account/dto/response/AccountCreateResult.java
  src/main/java/com/pet/domains/account/dto/response/AccountLoginResult.java
  src/main/java/com/pet/domains/account/dto/response/SampleResponse.java
  src/main/java/com/pet/domains/area/controller/CityController.java
  src/main/java/com/pet/domains/area/dto/CityReadResults.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/area/controller/CityControllerTest.java
Labels: feat

#79 [CP-74] feat: 실종/보호 게시물, 북마크 API Mocking
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/dto/request/MissingPostCreateParam.java
  src/main/java/com/pet/domains/post/dto/request/MissingPostUpdateParam.java
  src/main/java/com/pet/domains/post/dto/response/MissingPostReadResult.java
  src/main/java/com/pet/domains/post/dto/response/MissingPostReadResults.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
Labels: feat, review needed

#87 [CP-82] fix: 몸무게 필드 long에서 double로 수정
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
Labels: bug, review needed

#90 [CP-89] fix: api docs do first로 기존 파일 삭제
  build.gradle
Labels: bug, review needed

#92 [CP-91] fix: 포트 수정 및 clean build
  .github/workflows/deploy.yml
  build.gradle
  src/main/resources/application.yaml
Labels: bug

#98 [CP-97] fix: cors 풀기
  src/main/java/com/pet/common/config/WebMvcConfig.java
Labels: bug, review needed

#99 [CP-65] dev 서버 rds 연동 및 배포 수정
  .github/workflows/deploy.yml
  deploy-dev.sh
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: chore, review needed

#103 [CP-102] chore: post 패키지로 이동
  src/main/java/com/pet/domains/post/domain/MissingPostBookmark.java
  src/main/java/com/pet/domains/post/domain/ShelterPostBookmark.java
Labels: chore, review needed

#101 [CP-100] feat: 이미지 요청 로깅 추가
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/dto/request/AccountCreateParam.java
  src/main/java/com/pet/domains/account/dto/request/AccountUpdateParam.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/dto/request/MissingPostCreateParam.java
  src/main/java/com/pet/domains/post/dto/request/MissingPostUpdateParam.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
Labels: feat, review needed

#104 [CP-80] rest docs 경량화 & 커스텀 템플릿 추가
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/pet/common/response/ApiResponse.java
  src/main/java/com/pet/domains/EnumType.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/controller/MissingPostsController.java
  src/main/java/com/pet/domains/post/domain/NeuteredType.java
  src/main/java/com/pet/domains/post/domain/SexType.java
  src/main/java/com/pet/domains/post/domain/ShelterSexType.java
  src/main/java/com/pet/domains/post/domain/Status.java
  src/test/java/com/pet/common/response/ApiResponseTest.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
  src/test/java/com/pet/domains/animal/controller/AnimalControllerTest.java
  src/test/java/com/pet/domains/area/controller/CityControllerTest.java
  src/test/java/com/pet/domains/comment/controller/CommentControllerTest.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
  src/test/java/com/pet/domains/docs/CustomResponseFieldsSnippet.java
  src/test/java/com/pet/domains/docs/controller/CommonDocumentationController.java
  src/test/java/com/pet/domains/docs/controller/CommonDocumentationControllerTest.java
  src/test/java/com/pet/domains/docs/dto/CommonDocumentationResults.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
  src/test/java/com/pet/domains/post/controller/MissingPostsControllerTest.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
  src/test/java/com/pet/domains/statistics/controller/PostStatisticsControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/custom-response-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: feat, review needed

#107 [CP-106 ] fix: 배포 관련 환경변수 & docs 이슈 수정
  .github/workflows/deploy.yml
  build.gradle
  deploy-dev.sh
  src/main/resources/static/docs/index.html
Labels: bug, review needed

#110 [CP-96] feat: S3 이미지 업로드 세팅
  build.gradle
  src/main/java/com/pet/common/s3/controller/FileUploadController.java
  src/main/java/com/pet/common/s3/service/FileUploadService.java
  src/main/java/com/pet/common/s3/service/S3UploadService.java
  src/main/java/com/pet/common/s3/service/UploadService.java
  src/main/resources/application.yml
Labels: feat, review needed

#112 [CP-111] fix: access, secret 삭제
  src/main/resources/application.yml
Labels: bug

#113 [CP-109] docs: 게시물 조회 토큰 삭제 및 access header 추가
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
Labels: chore, review needed

#116 [CP-85] 시큐리티 세팅
  build.gradle
  src/main/java/com/pet/Application.java
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/common/config/WebMvcConfig.java
  src/main/java/com/pet/common/interceptor/JwtAuthenticationInterceptor.java
  src/main/java/com/pet/common/jwt/Jwt.java
  src/main/java/com/pet/common/jwt/JwtAuthentication.java
  src/main/java/com/pet/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/pet/common/jwt/JwtAuthenticationProvider.java
  src/main/java/com/pet/common/jwt/JwtAuthenticationToken.java
  src/main/java/com/pet/common/property/JwtProperty.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/domain/SignStatus.java
  src/main/java/com/pet/domains/account/repository/AccountRepository.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/auth/domain/Group.java
  src/main/java/com/pet/domains/auth/domain/GroupPermission.java
  src/main/java/com/pet/domains/auth/domain/Permission.java
  src/main/java/com/pet/domains/auth/repository/GroupPermissionRepository.java
  src/main/java/com/pet/domains/auth/repository/GroupRepository.java
  src/main/java/com/pet/domains/auth/repository/PermissionRepository.java
  src/main/java/com/pet/domains/post/domain/PostRepository.java
  src/main/resources/application.yml
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
Labels: feat, answer needed

#118 [CP-117]fix: 디비 네이밍 수정
  src/main/java/com/pet/domains/auth/domain/Group.java
Labels: bug

#120 [CP-119]fix: cors문제 및 패스워드 인증 문제 수정
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/common/config/WebMvcConfig.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/auth/repository/GroupRepository.java
  src/main/java/com/pet/domains/auth/repository/PermissionRepository.java
Labels: bug, merge needed

#124 [CP-123] feat: Jwt Mocking Test, jwt 토큰 인증 및 회원 객체 조회 관심 분리
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/common/config/WebMvcConfig.java
  src/main/java/com/pet/common/exception/AuthenticationException.java
  src/main/java/com/pet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/domain/LoginAccount.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/auth/HandlerMethodResolverArgumentConfig.java
  src/main/java/com/pet/domains/auth/controller/argumentresolver/JwtAuthenticationArgumentResolver.java
  src/test/java/com/pet/domains/account/WithAccount.java
  src/test/java/com/pet/domains/account/WithAccountSecurityContextFactory.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
Labels: feat

#121 [CP-108] 보호소 동물 게시글 api 요청 서비스 추가
  build.gradle
  src/main/java/com/pet/common/property/ShelterProperties.java
  src/main/java/com/pet/domains/post/domain/SexType.java
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/post/domain/ShelterSexType.java
  src/main/java/com/pet/domains/post/dto/request/ShelterPostCreateParams.java
  src/main/java/com/pet/domains/post/dto/response/ShelterApiPageResult.java
  src/main/java/com/pet/domains/post/repository/ShelterPostRepository.java
  src/main/java/com/pet/domains/post/service/ShelterApiService.java
  src/main/java/com/pet/domains/post/service/ShelterService.java
  src/main/resources/application.yml
  src/test/java/com/pet/domains/docs/controller/CommonDocumentationController.java
  src/test/java/com/pet/domains/docs/controller/CommonDocumentationControllerTest.java
Labels: feat, review needed

#127 [CP/126] fix: 빈 순환참조 해결
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/auth/service/AuthenticationService.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
Labels: bug

#128 [CP-125] 공통 예외처리 작업 및 리팩토링
  src/main/java/com/pet/common/exception/ExceptionHandlerAdvice.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/pet/common/exception/httpexception/BadRequestException.java
  src/main/java/com/pet/common/exception/httpexception/InternalServerException.java
  src/main/java/com/pet/common/exception/httpexception/NotFoundException.java
  src/main/java/com/pet/common/exception/httpexception/UnauthorizedException.java
  src/main/java/com/pet/common/jwt/JwtAuthenticationProvider.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/auth/controller/argumentresolver/JwtAuthenticationArgumentResolver.java
Labels: 리뷰 요청, feat, refactoring

#130 [CP-122] feat: 동물,품종 api 데이터 서비스 추가
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/common/property/ShelterProperties.java
  src/main/java/com/pet/domains/animal/domain/Animal.java
  src/main/java/com/pet/domains/animal/domain/AnimalKind.java
  src/main/java/com/pet/domains/animal/dto/request/AnimalKindCreateParams.java
  src/main/java/com/pet/domains/animal/dto/response/AnimalKindApiPageResults.java
  src/main/java/com/pet/domains/animal/repository/AnimalKindRepository.java
  src/main/java/com/pet/domains/animal/repository/AnimalRepository.java
  src/main/java/com/pet/domains/animal/service/AnimalKindService.java
  src/main/java/com/pet/domains/post/dto/request/ShelterPostCreateParams.java
  src/main/java/com/pet/domains/post/dto/response/ShelterApiPageResult.java
  src/main/java/com/pet/domains/post/service/ShelterApiService.java
  src/main/resources/application.yml
  src/test/java/com/pet/domains/animal/controller/AnimalKindControllerTest.java
  src/test/java/com/pet/domains/animal/repository/AnimalKindRepositoryTest.java
  src/test/java/com/pet/domains/animal/repository/AnimalRepositoryTest.java
Labels: feat, review needed

#133 [CP-131] feat: 시도 open api 서비스 추가 & data migrate
  src/main/java/com/pet/Application.java
  src/main/java/com/pet/domains/area/domain/City.java
  src/main/java/com/pet/domains/area/dto/request/CityCreateParams.java
  src/main/java/com/pet/domains/area/dto/response/CityApiPageResults.java
  src/main/java/com/pet/domains/area/mapper/CityMapper.java
  src/main/java/com/pet/domains/area/repository/CityRepository.java
  src/main/java/com/pet/domains/area/service/CityService.java
  src/main/java/com/pet/domains/post/service/ShelterApiService.java
  src/main/resources/application.yml
Labels: feat, merge needed

#137 [CP-136] DDL 문제 수정
  src/main/java/com/pet/domains/account/domain/SignEmail.java
  src/main/java/com/pet/domains/account/repository/SignEmailRepository.java
  src/main/java/com/pet/domains/account/service/AccountService.java
Labels: bug, merge needed

#141 [CP-140] 스프링 애플리케이션 타임존 설정
  src/main/java/com/pet/Application.java
  src/main/java/com/pet/domains/post/service/ShelterApiService.java
Labels: chore, review needed

#143 [Cp-142] 데일리 쉘터 게시글 스케줄러 잡 추가
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/animal/dto/response/AnimalKindApiPageResults.java
  src/main/java/com/pet/domains/animal/repository/AnimalRepository.java
  src/main/java/com/pet/domains/animal/service/AnimalKindService.java
  src/main/java/com/pet/domains/area/dto/response/CityApiPageResults.java
  src/main/java/com/pet/domains/area/dto/response/TownApiPageResults.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/post/dto/request/ShelterPostCreateParams.java
  src/main/java/com/pet/domains/post/dto/response/ShelterApiPageResult.java
  src/main/java/com/pet/domains/post/mapper/ShelterPostMapper.java
  src/main/java/com/pet/domains/post/service/ShelterApiService.java
  src/main/java/com/pet/domains/post/service/ShelterService.java
  src/main/resources/application.yml
  src/main/resources/data-h2.sql
  src/test/java/com/pet/domains/animal/repository/AnimalRepositoryTest.java
Labels: feat, review needed

#148 [CP-147] shelter post 필드들 nullable 하도록 수정
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/post/service/ShelterService.java
  src/main/resources/application-dev.yml
Labels: feat, review needed

#144 [CP-134] feat: 구글, 네이버 로그인
  build.gradle
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/auth/oauth2/GoogleUser.java
  src/main/java/com/pet/domains/auth/oauth2/Oauth2User.java
  src/main/java/com/pet/domains/auth/oauth2/ProviderType.java
  src/main/java/com/pet/domains/image/domain/Image.java
  src/main/resources/application.yml
  src/test/java/com/pet/domains/account/WithAccountSecurityContextFactory.java
Labels: feat, answer needed

#149 [CP-145] 동물 목록 조회 api 추가
  src/main/java/com/pet/domains/animal/controller/AnimalController.java
  src/main/java/com/pet/domains/animal/domain/Animal.java
  src/main/java/com/pet/domains/animal/dto/response/AnimalReadResults.java
  src/main/java/com/pet/domains/animal/mapper/AnimalMapper.java
  src/main/java/com/pet/domains/animal/repository/AnimalRepository.java
  src/main/java/com/pet/domains/animal/service/AnimalService.java
  src/test/java/com/pet/domains/animal/controller/AnimalControllerTest.java
  src/test/java/com/pet/domains/animal/controller/AnimalKindControllerTest.java
  src/test/java/com/pet/domains/animal/repository/AnimalRepositoryTest.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
Labels: feat, review needed

#155 [CP-152] 보호소 게시글 북마크 등록 api 추가
  lombok.config
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/animal/domain/Animal.java
  src/main/java/com/pet/domains/animal/domain/AnimalKind.java
  src/main/java/com/pet/domains/post/controller/ShelterPostController.java
  src/main/java/com/pet/domains/post/domain/ShelterPostBookmark.java
  src/main/java/com/pet/domains/post/repository/ShelterPostBookmarkRepository.java
  src/main/java/com/pet/domains/post/service/ShelterApiService.java
  src/main/java/com/pet/domains/post/service/ShelterPostBookmarkService.java
  src/main/java/com/pet/domains/post/service/ShelterPostService.java
  src/test/java/com/pet/domains/animal/service/AnimalServiceTest.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
  src/test/java/com/pet/domains/post/service/ShelterPostBookmarkServiceTest.java
Labels: feat, review needed

#161 [CP-160] chore: sql 쿼리 로그 남기기
  src/main/resources/application.yml
Labels: chore

#165 [CP-159] 이메일 전송 문제
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/domain/SignEmail.java
  src/main/java/com/pet/domains/account/dto/request/AccountSignUpParam.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/infra/HtmlMailSender.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/account/repository/SignEmailRepositoryTest.java
Labels: bug

#167 [CP-166] chore: 사용하지 않는 엔티티 삭제
  src/main/java/com/pet/domains/post/domain/MissingPostImage.java
Labels: chore

#163 [CP-157] 보호소 게시글 북마크 해제 api
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/post/controller/ShelterPostController.java
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/post/repository/ShelterPostBookmarkRepository.java
  src/main/java/com/pet/domains/post/service/ShelterPostBookmarkService.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
  src/test/java/com/pet/domains/post/repository/ShelterPostBookmarkRepositoryTest.java
  src/test/java/com/pet/domains/post/service/ShelterPostBookmarkServiceTest.java
Labels: feat, review needed

#169 [CP-154] 관심 지역 설정 api
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/dto/request/AccountAreaUpdateParam.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/area/domain/InterestArea.java
  src/main/java/com/pet/domains/area/repository/InterestAreaRepository.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
Labels: feat, merge needed

#177 [CP-150] 회원 정보 수정 api
  src/docs/asciidoc/index.adoc
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/dto/request/AccountPasswordParam.java
  src/main/java/com/pet/domains/account/dto/request/AccountUpdateParam.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
Labels: feat

#174 [CP-173] 댓글 생성 api
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/comment/controller/CommentController.java
  src/main/java/com/pet/domains/comment/domain/Comment.java
  src/main/java/com/pet/domains/comment/dto/request/CommentCreateParam.java
  src/main/java/com/pet/domains/comment/repository/CommentRepository.java
  src/main/java/com/pet/domains/comment/service/CommentService.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/test/java/com/pet/domains/comment/controller/CommentControllerTest.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
Labels: feat, review needed

#170 [CP-156] feat: 실종/보호 게시물 삭제 API 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/auth/controller/argumentresolver/JwtAuthenticationArgumentResolver.java
  src/main/java/com/pet/domains/comment/repository/CommentRepository.java
  src/main/java/com/pet/domains/image/repository/PostImageRepository.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/dto/request/MissingPostCreateParam.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/tag/domain/Tag.java
  src/main/java/com/pet/domains/tag/repository/PostTagRepository.java
  src/main/java/com/pet/domains/tag/service/TagService.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
  src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
Labels: feat

#181 [CP-178] 커스텀 예외 코드 추가
  src/main/java/com/pet/common/exception/AuthenticationException.java
  src/main/java/com/pet/common/exception/ExceptionHandlerAdvice.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/common/exception/httpexception/AuthenticationException.java
  src/main/java/com/pet/common/exception/httpexception/BadRequestException.java
  src/main/java/com/pet/common/exception/httpexception/BaseHttpException.java
  src/main/java/com/pet/common/exception/httpexception/ConflictException.java
  src/main/java/com/pet/common/exception/httpexception/InternalServerException.java
  src/main/java/com/pet/common/exception/httpexception/NotFoundException.java
  src/main/java/com/pet/common/exception/httpexception/UnauthorizedException.java
  src/main/java/com/pet/common/response/ErrorResponse.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
Labels: feat, answer needed, merge needed

#183 [CP-182] fix: 실종/보호 게시물 Service bug 해결
  src/main/java/com/pet/domains/image/domain/PostImage.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/tag/domain/PostTag.java
  src/main/java/com/pet/domains/tag/domain/Tag.java
Labels: bug

#180 [CP-179] query dsl 세팅
  .github/workflows/gradle.yml
  build.gradle
Labels: chore

#187 [CP-186] account sign status 안쓰는 필드삭제
  build.gradle
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/domain/SignStatus.java
  src/test/java/com/pet/domains/account/WithAccountSecurityContextFactory.java
  src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
Labels: feat

#188 [CP-171] 실종/보호 게시물 북마크 등록 API
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/domain/MissingPostBookmark.java
  src/main/java/com/pet/domains/post/repository/MissingPostBookmarkRepository.java
  src/main/java/com/pet/domains/post/service/MissingPostBookmarkService.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
  src/test/java/com/pet/domains/post/service/MissingPostBookmarkServiceTest.java
Labels: feat

#191 [CP-185] docs: README 초안 작성
  README.md
Labels: chore

#184 [CP-158] 회원 관심 지역 조회 api
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/domain/Provider.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/area/domain/InterestArea.java
  src/main/java/com/pet/domains/area/mapper/InterestAreaMapper.java
  src/main/java/com/pet/domains/area/repository/InterestAreaRepository.java
  src/test/java/com/pet/domains/account/WithAccountSecurityContextFactory.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/area/repository/InterestAreaRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/ShelterPostBookmarkRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/ShelterPostRepositoryTest.java
  src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
Labels: feat

#192 [CP-190] 실종/보호 게시물 북마크 삭제 API
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/domain/MissingPostBookmark.java
  src/main/java/com/pet/domains/post/repository/MissingPostBookmarkRepository.java
  src/main/java/com/pet/domains/post/service/MissingPostBookmarkService.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostBookmarkRepositoryTest.java
  src/test/java/com/pet/domains/post/service/MissingPostBookmarkServiceTest.java
Labels: feat

#193 [CP-176] 게시글 통계 데이터 cron job 추가
  src/main/java/com/pet/domains/post/dto/request/ShelterPostCreateParams.java
  src/main/java/com/pet/domains/statistics/domain/PostStatistics.java
  src/main/java/com/pet/domains/statistics/mapper/PostStatisticsMapper.java
  src/main/java/com/pet/domains/statistics/repository/PostCountByStatus.java
  src/main/java/com/pet/domains/statistics/repository/PostStatisticsRepository.java
  src/main/java/com/pet/domains/statistics/service/PostStatisticsService.java
  src/test/java/com/pet/domains/statistics/service/PostStatisticsServicesTest.java
Labels: feat, review needed

#202 [CP-201] 댓글 삭제 api 구현
  src/main/java/com/pet/domains/comment/controller/CommentController.java
  src/main/java/com/pet/domains/comment/domain/Comment.java
  src/main/java/com/pet/domains/comment/repository/CommentRepository.java
  src/main/java/com/pet/domains/comment/service/CommentService.java
  src/test/java/com/pet/domains/comment/controller/CommentControllerTest.java
  src/test/java/com/pet/domains/comment/repository/CommentRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
Labels: feat, review needed

#197 [CP-194] feat: 이미지 수정 api
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
Labels: feat, review needed

#199 [CP-198] 알림 삭제 api
  src/main/java/com/pet/domains/account/controller/NotificationController.java
  src/main/java/com/pet/domains/account/domain/Notification.java
  src/main/java/com/pet/domains/account/repository/NotificationRepository.java
  src/main/java/com/pet/domains/account/service/NotificationService.java
  src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
  src/test/java/com/pet/domains/account/repository/NotificationRepositoryTest.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
Labels: feat, review needed

#204 [CP-189] feat: jwt 확인 api, 예외 처리
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/common/exception/ExceptionHandlerAdvice.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/common/exception/httpexception/UnauthorizedException.java
  src/main/java/com/pet/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/pet/common/jwt/JwtMockToken.java
  src/main/java/com/pet/domains/auth/controller/AuthController.java
  src/main/java/com/pet/domains/auth/controller/argumentresolver/JwtAuthenticationArgumentResolver.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
  src/test/java/com/pet/domains/comment/controller/CommentControllerTest.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
  src/test/java/com/pet/domains/statistics/controller/PostStatisticsControllerTest.java
Labels: feat, review needed

#200 [CP-196] 보호소 게시글 단건 조회 api 구현
  src/main/java/com/pet/domains/post/controller/ShelterPostController.java
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/post/dto/response/ShelterPostReadResult.java
  src/main/java/com/pet/domains/post/mapper/ShelterPostMapper.java
  src/main/java/com/pet/domains/post/repository/ShelterPostRepository.java
  src/main/java/com/pet/domains/post/service/ShelterPostBookmarkService.java
  src/main/java/com/pet/domains/post/service/ShelterPostService.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
  src/test/java/com/pet/domains/post/repository/ShelterPostRepositoryTest.java
Labels: feat, review needed

#206 [CP-205] 게시글 통계 데이터 조회 api 추가
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/statistics/controller/PostStatisticsController.java
  src/main/java/com/pet/domains/statistics/dto/response/PostStatisticsReadResult.java
  src/main/java/com/pet/domains/statistics/mapper/PostStatisticsMapper.java
  src/main/java/com/pet/domains/statistics/repository/PostStatisticsRepository.java
  src/main/java/com/pet/domains/statistics/service/PostStatisticsService.java
  src/test/java/com/pet/domains/account/dto/AccountValidationTest.java
  src/test/java/com/pet/domains/animal/repository/AnimalKindRepositoryTest.java
  src/test/java/com/pet/domains/animal/repository/AnimalRepositoryTest.java
  src/test/java/com/pet/domains/animal/service/AnimalServiceTest.java
  src/test/java/com/pet/domains/area/repository/CityRepositoryTest.java
  src/test/java/com/pet/domains/area/repository/InterestAreaRepositoryTest.java
  src/test/java/com/pet/domains/area/repository/TownRepositoryTest.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
  src/test/java/com/pet/domains/docs/controller/CommonDocumentationControllerTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostBookmarkRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/ShelterPostBookmarkRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/ShelterPostRepositoryTest.java
  src/test/java/com/pet/domains/post/service/ShelterPostBookmarkServiceTest.java
  src/test/java/com/pet/domains/statistics/controller/PostStatisticsControllerTest.java
  src/test/java/com/pet/domains/statistics/repository/PostStatisticsRepositoryTest.java
  src/test/java/com/pet/domains/statistics/service/PostStatisticsServicesTest.java
  src/test/java/com/pet/domains/tag/repository/TagRepositoryTest.java
Labels: feat, review needed

#212 [CP-210] 에러 응답 안내 api
  src/main/java/com/pet/common/exception/controller/ExceptionController.java
Labels: review needed, answer needed

#211 [CP-209] feat: 시도/시군구 조회 api
  src/main/java/com/pet/domains/area/controller/CityController.java
  src/main/java/com/pet/domains/area/domain/City.java
  src/main/java/com/pet/domains/area/mapper/CityMapper.java
  src/main/java/com/pet/domains/area/repository/CityRepository.java
  src/main/java/com/pet/domains/area/service/CityService.java
  src/main/java/com/pet/domains/area/service/TownService.java
  src/test/java/com/pet/domains/area/controller/CityControllerTest.java
  src/test/java/com/pet/domains/area/repository/CityRepositoryTest.java
  src/test/java/com/pet/domains/docs/BaseDocumentationTest.java
Labels: feat, review needed

#216 [CP-214] feat: 회원 정보 조회 api
  src/docs/asciidoc/index.adoc
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/dto/response/AccountReadResult.java
  src/main/java/com/pet/domains/account/mapper/AccountMapper.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
Labels: feat, answer needed

#215 [CP-203] 댓글 수정 api 추가
  src/main/java/com/pet/domains/animal/repository/AnimalRepository.java
  src/main/java/com/pet/domains/comment/controller/CommentController.java
  src/main/java/com/pet/domains/comment/domain/Comment.java
  src/main/java/com/pet/domains/comment/dto/request/CommentUpdateParam.java
  src/main/java/com/pet/domains/comment/service/CommentService.java
  src/test/java/com/pet/domains/comment/controller/CommentControllerTest.java
Labels: feat, review needed

#221 [CP-220] feat: 권한이 필요한 요청에 토큰을 넣지 않는 경우 처리
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/common/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/pet/common/exception/ExceptionHandlerAdvice.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/common/exception/httpexception/ForbiddenException.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
Labels: feat, bug, review needed

#226 [CP-225] 유니크 제약조건 추가
  src/main/java/com/pet/domains/animal/domain/Animal.java
  src/main/java/com/pet/domains/animal/domain/AnimalKind.java
  src/main/java/com/pet/domains/area/domain/City.java
  src/main/java/com/pet/domains/area/domain/Town.java
  src/main/java/com/pet/domains/post/domain/MissingPostBookmark.java
  src/main/java/com/pet/domains/post/domain/ShelterPostBookmark.java
Labels: feat, review needed

#219 [CP-218] 북마크 카운트 증감 로직에 락처리 추가
  src/main/java/com/pet/common/util/OptimisticLockingHandlingUtils.java
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/post/repository/ShelterPostBookmarkRepository.java
  src/main/java/com/pet/domains/post/service/ShelterPostBookmarkService.java
  src/test/java/com/pet/domains/LockTest.java
  src/test/java/com/pet/domains/post/repository/ShelterPostRepositoryTest.java
  src/test/java/com/pet/domains/post/service/ShelterPostBookmarkServiceTest.java
Labels: feat, review needed

#227 [CP-222] 임시 비밀번호 전송 api
  src/docs/asciidoc/index.adoc
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/infra/EmailMessage.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
Labels: feat

#231 [CP-195] 실종/보호 게시글 리스트 조회 API
  src/docs/asciidoc/index.adoc
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/dto/response/MissingPostReadResults.java
  src/main/java/com/pet/domains/post/mapper/MissingPostMapper.java
  src/main/java/com/pet/domains/post/repository/MissingPostRepository.java
  src/main/java/com/pet/domains/post/repository/MissingPostWithIsBookmark.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/tag/domain/PostTag.java
  src/main/java/com/pet/domains/tag/service/PostTagService.java
  src/main/java/com/pet/domains/tag/service/TagService.java
  src/test/java/com/pet/domains/area/repository/CityRepositoryTest.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
  src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
Labels: feat, refactoring

#229 [CP-228] feat: 회원 조회 이미지 추가 조회
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/dto/response/AccountReadResult.java
  src/main/java/com/pet/domains/account/mapper/AccountMapper.java
  src/main/java/com/pet/domains/account/repository/AccountRepository.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
Labels: feat

#242 [CP-241] CORS 이슈 수정
  src/main/java/com/pet/common/config/WebMvcConfig.java
Labels: bug

#230 [CP-223] feat: 알림 클릭 api
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/account/controller/NotificationController.java
  src/main/java/com/pet/domains/account/domain/Notification.java
  src/main/java/com/pet/domains/account/repository/NotificationRepository.java
  src/main/java/com/pet/domains/account/service/NotificationService.java
  src/test/java/com/pet/domains/account/repository/NotificationRepositoryTest.java
Labels: feat

#236 [CP-207] 보호소 게시글 조회 query dsl 사용
  src/main/java/com/pet/common/config/QuerydslConfig.java
  src/main/java/com/pet/common/util/SampleUtil.java
  src/main/java/com/pet/domains/post/dto/response/ShelterPostReadResult.java
  src/main/java/com/pet/domains/post/mapper/ShelterPostMapper.java
  src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepository.java
  src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepositoryImpl.java
  src/main/java/com/pet/domains/post/repository/ShelterPostRepository.java
  src/main/java/com/pet/domains/post/repository/ShelterPostWithIsBookmark.java
  src/main/java/com/pet/domains/post/repository/projection/ShelterPostWithIsBookmark.java
  src/main/java/com/pet/domains/post/service/ShelterPostService.java
  src/test/java/com/pet/domains/account/repository/NotificationRepositoryTest.java
  src/test/java/com/pet/domains/account/repository/SignEmailRepositoryTest.java
  src/test/java/com/pet/domains/animal/repository/AnimalKindRepositoryTest.java
  src/test/java/com/pet/domains/animal/repository/AnimalRepositoryTest.java
  src/test/java/com/pet/domains/area/repository/CityRepositoryTest.java
  src/test/java/com/pet/domains/area/repository/InterestAreaRepositoryTest.java
  src/test/java/com/pet/domains/area/repository/TownRepositoryTest.java
  src/test/java/com/pet/domains/comment/repository/CommentRepositoryTest.java
  src/test/java/com/pet/domains/docs/dto/CommonDocumentationResults.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostBookmarkRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/ShelterPostBookmarkRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/ShelterPostRepositoryTest.java
  src/test/java/com/pet/domains/statistics/repository/PostStatisticsRepositoryTest.java
  src/test/java/com/pet/domains/tag/repository/TagRepositoryTest.java
Labels: refactoring, review needed

#238 [CP-217] 댓글 카운트 증감 로직 추가
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/comment/domain/Comment.java
  src/main/java/com/pet/domains/comment/repository/CommentRepository.java
  src/main/java/com/pet/domains/comment/service/CommentService.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/test/java/com/pet/domains/comment/repository/CommentRepositoryTest.java
Labels: feat, review needed

#245 [CP-234] 회원 관련 프론트팀으로부터 요청사항 반영
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/dto/request/AccountUpdateParam.java
  src/main/java/com/pet/domains/account/dto/response/AccountAreaReadResults.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/area/domain/InterestArea.java
  src/main/java/com/pet/domains/area/mapper/InterestAreaMapper.java
  src/main/java/com/pet/domains/area/repository/InterestAreaRepository.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
Labels: bug

#240 [CP-237] 실종/보호 게시글 북마크 카운트 증감 로직 추가
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/repository/MissingPostBookmarkRepository.java
  src/main/java/com/pet/domains/post/service/MissingPostBookmarkService.java
  src/test/java/com/pet/domains/post/repository/MissingPostBookmarkRepositoryTest.java
  src/test/java/com/pet/domains/post/service/MissingPostBookmarkServiceTest.java
Labels: feat

#258 [CP-257] 유니크 이슈 수정
  src/main/java/com/pet/domains/animal/domain/Animal.java
  src/main/java/com/pet/domains/animal/domain/AnimalKind.java
  src/main/java/com/pet/domains/area/domain/Town.java
Labels: feat, merge needed

#259 [CP-256] 실종/보호 게시물 Entity 연관관계 수정
  src/main/java/com/pet/domains/image/domain/PostImage.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
Labels: refactoring

#252 [CP-175] 실종 게시글의 댓글 페이지 조회 api 구현
  jffi13856073814497304600.dylib
  src/docs/asciidoc/index.adoc
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/domains/comment/domain/Comment.java
  src/main/java/com/pet/domains/comment/dto/response/CommentPageResults.java
  src/main/java/com/pet/domains/comment/mapper/CommentMapper.java
  src/main/java/com/pet/domains/comment/repository/CommentRepository.java
  src/main/java/com/pet/domains/comment/service/CommentService.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/dto/response/MissingPostCommentPageResults.java
  src/test/java/com/pet/domains/comment/controller/CommentControllerTest.java
  src/test/java/com/pet/domains/comment/repository/CommentRepositoryTest.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
Labels: feat, review needed

#266 [CP-265] fix: 실종/보호 게시물 저장 에러 수정
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/repository/MissingPostRepository.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
Labels: bug, 선 머지 후 리뷰!!

#267 [CP-262] 회원 관련 버그 수정 및 알림 조회 api
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/controller/NotificationController.java
  src/main/java/com/pet/domains/account/domain/Account.java
  src/main/java/com/pet/domains/account/dto/response/NotificationReadResults.java
  src/main/java/com/pet/domains/account/mapper/NotificationMapper.java
  src/main/java/com/pet/domains/account/repository/NotificationRepository.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/account/service/NotificationService.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
  src/test/java/com/pet/domains/account/repository/NotificationRepositoryTest.java
Labels: feat, bug, 선 머지 후 리뷰!!

#254 [Cp-239] feat: version 이슈 수정
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/post/service/MissingPostBookmarkService.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/tag/service/TagService.java
Labels: bug, review needed

#261 [CP-260] docs host name 추가
  src/docs/asciidoc/index.adoc
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
  src/test/java/com/pet/domains/animal/controller/AnimalControllerTest.java
  src/test/java/com/pet/domains/area/controller/CityControllerTest.java
  src/test/java/com/pet/domains/comment/controller/CommentControllerTest.java
  src/test/java/com/pet/domains/docs/utils/ApiDocumentUtils.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
  src/test/java/com/pet/domains/statistics/controller/PostStatisticsControllerTest.java
Labels: feat, review needed

#268 [CP-248] 회원의 게시물 조회 api
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/dto/response/AccountMissingPostPageResults.java
  src/main/java/com/pet/domains/account/mapper/AccountMapper.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/domain/PostRepository.java
  src/main/java/com/pet/domains/post/repository/MissingPostRepository.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
Labels: feat

#269 [CP-151] 실종/보호 게시물 단건 조회 API
  jffi3422096377270731203.dylib
  src/docs/asciidoc/index.adoc
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/image/domain/PostImage.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/dto/response/MissingPostReadResult.java
  src/main/java/com/pet/domains/post/mapper/MissingPostMapper.java
  src/main/java/com/pet/domains/post/repository/MissingPostRepository.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/tag/domain/PostTag.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
  src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
Labels: feat

#275 [CP-273] 실종/보호 게시글 response, request 필드명 통일 및 게시글 등록 오류 해결
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/common/s3/service/FileUploadService.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/dto/request/MissingPostCreateParam.java
  src/main/java/com/pet/domains/post/dto/request/MissingPostUpdateParam.java
  src/main/java/com/pet/domains/post/dto/response/MissingPostReadResult.java
  src/main/java/com/pet/domains/post/dto/response/MissingPostReadResults.java
  src/main/java/com/pet/domains/post/mapper/MissingPostMapper.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
Labels: chore

#276 [CP-207] 보호소 게시글 검색 필터링 추가
  jffi13856073814497304600.dylib
  jffi3422096377270731203.dylib
  src/main/java/com/pet/common/exception/ExceptionHandlerAdvice.java
  src/main/java/com/pet/domains/post/controller/ShelterPostController.java
  src/main/java/com/pet/domains/post/dto/request/MissingPostCreateParam.java
  src/main/java/com/pet/domains/post/dto/request/MissingPostUpdateParam.java
  src/main/java/com/pet/domains/post/dto/response/ShelterPostPageResults.java
  src/main/java/com/pet/domains/post/dto/response/ShelterPostReadResult.java
  src/main/java/com/pet/domains/post/dto/serach/PostSearchParam.java
  src/main/java/com/pet/domains/post/mapper/ShelterPostMapper.java
  src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepository.java
  src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepositoryImpl.java
  src/main/java/com/pet/domains/post/repository/ShelterPostRepository.java
  src/main/java/com/pet/domains/post/repository/projection/ShelterPostWithIsBookmark.java
  src/main/java/com/pet/domains/post/service/ShelterPostService.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
  src/test/java/com/pet/domains/post/repository/ShelterPostRepositoryTest.java
Labels: feat, review needed

#279 [CP-271] Tag, MissingPost, ShelterPost 낙관적 락 추가
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/tag/domain/Tag.java
Labels: feat, review needed

#277 [CP-270] 삭제된 댓글 조회 & 내용 처리
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/domains/comment/domain/Comment.java
  src/main/java/com/pet/domains/comment/repository/CommentRepository.java
  src/main/java/com/pet/domains/comment/service/CommentService.java
  src/test/java/com/pet/domains/comment/repository/CommentRepositoryTest.java
Labels: feat, review needed

#281 [CP-280] 댓글 생성, 수정시 바디 리턴
  src/main/java/com/pet/domains/comment/controller/CommentController.java
  src/main/java/com/pet/domains/comment/dto/response/CommentWriteResult.java
  src/main/java/com/pet/domains/comment/mapper/CommentMapper.java
  src/main/java/com/pet/domains/comment/service/CommentService.java
  src/test/java/com/pet/domains/comment/controller/CommentControllerTest.java
Labels: feat, review needed

#285 [CP-284] 나의 알림만 조회하도록 수정 & 응답 포맷 추가
  src/main/java/com/pet/domains/account/controller/NotificationController.java
  src/main/java/com/pet/domains/account/dto/response/NotificationReadResults.java
  src/main/java/com/pet/domains/account/mapper/NotificationMapper.java
  src/main/java/com/pet/domains/account/repository/NotificationRepository.java
  src/main/java/com/pet/domains/account/service/NotificationService.java
  src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
Labels: feat, review needed

#283 [CP-272] 게시물 생성시 해당 지역을 관심등록한 유저들에게 알림 생성 서비스 구현
  src/main/java/com/pet/Application.java
  src/main/java/com/pet/domains/account/domain/Notification.java
  src/main/java/com/pet/domains/account/repository/AccountRepository.java
  src/main/java/com/pet/domains/account/service/NotificationAsyncService.java
  src/main/java/com/pet/domains/area/domain/City.java
  src/main/java/com/pet/domains/area/domain/Town.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/mapper/MissingPostMapper.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/tag/service/PostTagService.java
  src/test/java/com/pet/domains/account/repository/AccountRepositoryTest.java
  src/test/java/com/pet/domains/account/repository/NotificationRepositoryTest.java
  src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
Labels: feat, review needed

#288 [CP-251] feat: 회원삭제 api
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/account/service/AccountService.java
  src/main/java/com/pet/domains/post/repository/MissingPostRepository.java
Labels: feat

#274 [CP-249] 실종/보호 회원 북마크 게시물 조회
  src/main/java/com/pet/domains/account/controller/AccountController.java
  src/main/java/com/pet/domains/post/mapper/MissingPostMapper.java
  src/main/java/com/pet/domains/post/mapper/ShelterPostMapper.java
  src/main/java/com/pet/domains/post/repository/MissingPostRepository.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/post/service/ShelterApiService.java
  src/main/java/com/pet/domains/post/service/ShelterPostService.java
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
Labels: feat

#290 [CP-289] 댓글 응답에 deleted 필드 추가
  src/main/java/com/pet/domains/comment/dto/response/CommentPageResults.java
  src/main/java/com/pet/domains/comment/dto/response/CommentWriteResult.java
  src/test/java/com/pet/domains/comment/controller/CommentControllerTest.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
Labels: feat, review needed, 선 머지 후 리뷰!!

#292 [CP-291] 알림 조회 응답 필드 누락 수정
  src/main/java/com/pet/domains/account/dto/response/NotificationReadResults.java
  src/main/java/com/pet/domains/account/mapper/NotificationMapper.java
  src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
Labels: bug, review needed, 선 머지 후 리뷰!!

#295 [CP-293] feat: 알림 조회시 id도 조회되도록 수정
  src/main/java/com/pet/domains/account/dto/response/NotificationReadResults.java
  src/main/java/com/pet/domains/account/service/NotificationService.java
  src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
Labels: feat

#296 [CP-146] chore: jwt 시크릿하게 관리
  src/main/resources/application.yml
Labels: chore

#299 [CP-298] 알림 전체 삭제
  src/docs/asciidoc/index.adoc
  src/main/java/com/pet/domains/account/controller/NotificationController.java
  src/main/java/com/pet/domains/account/repository/NotificationRepository.java
  src/main/java/com/pet/domains/account/service/NotificationService.java
  src/test/java/com/pet/domains/account/controller/NotificationControllerTest.java
Labels: feat, merge needed

#301 [CP-287] 댓글, 북마크, 태그 카운트는 formula 사용 & 조회수만 낙관적 락 처리
  src/main/java/com/pet/common/exception/ExceptionHandlerAdvice.java
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/common/util/OptimisticLockingHandlingUtils.java
  src/main/java/com/pet/domains/comment/service/CommentService.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/domain/ShelterPost.java
  src/main/java/com/pet/domains/post/repository/MissingPostBookmarkRepository.java
  src/main/java/com/pet/domains/post/service/MissingPostBookmarkService.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/post/service/ShelterPostBookmarkService.java
  src/main/java/com/pet/domains/tag/domain/Tag.java
  src/main/java/com/pet/domains/tag/service/TagService.java
  src/test/java/com/pet/domains/post/repository/MissingPostBookmarkRepositoryTest.java
  src/test/java/com/pet/domains/post/repository/MissingPostRepositoryTest.java
  src/test/java/com/pet/domains/post/service/MissingPostBookmarkServiceTest.java
  src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
  src/test/java/com/pet/domains/post/service/ShelterPostBookmarkServiceTest.java
  src/test/java/com/pet/domains/tag/repository/TagRepositoryTest.java
Labels: feat, review needed

#304 [CP-303] bean validation 메시지 오타 수정
  src/main/java/com/pet/domains/post/dto/request/MissingPostCreateParam.java
Labels: chore, review needed

#302 [CP-232] feat: 실종/보호 게시글 수정 API
  src/main/java/com/pet/common/exception/ExceptionMessage.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/dto/request/MissingPostUpdateParam.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/tag/repository/PostTagRepository.java
  src/test/java/com/pet/domains/account/repository/NotificationRepositoryTest.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
Labels: feat

#305 [CP-105] feat: 예외 응답 추가
  src/main/java/com/pet/common/exception/ExceptionHandlerAdvice.java
  src/main/java/com/pet/common/response/ErrorResponse.java
  src/main/resources/banner.txt
Labels: feat

#310 [CP-309] fix: offset 이슈 수정
  deploy-dev.sh
  src/main/java/com/pet/common/config/CustomPageableConfiguration.java
  src/main/java/com/pet/domains/post/repository/MissingPostCustomRepositoryImpl.java
  src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepositoryImpl.java
Labels: bug, review needed

#313 [CP-312] No auth 요청시 oauth 리다이렉트 이슈 수정
  src/main/java/com/pet/common/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/pet/common/exception/ExceptionHandlerAdvice.java
  src/main/java/com/pet/domains/EntryExceptionController.java
Labels: bug, review needed

#315 [CP-314] fix: city, town 바뀐 이슈 수정
  src/main/java/com/pet/domains/account/mapper/AccountMapper.java
Labels: bug

#319 [CP-316] 실종/보호 게시물 수정 이슈 해결
  src/main/java/com/pet/domains/post/service/MissingPostService.java
Labels: bug

#320 [CP-317] 보호 장소 응답 필드 추가
  src/main/java/com/pet/domains/post/dto/response/ShelterPostReadResult.java
  src/test/java/com/pet/domains/post/controller/ShelterPostControllerTest.java
Labels: bug, review needed

#322 fix: password nullable하게 수정
  src/main/java/com/pet/domains/account/domain/Account.java
Labels: bug

#311 [CP-306] 동물, 지역 정보 레디스 캐싱
  build.gradle
  src/main/java/com/pet/common/config/RedisCachingConfig.java
  src/main/java/com/pet/common/config/RedisConfig.java
  src/main/java/com/pet/common/property/RedisProperties.java
  src/main/java/com/pet/domains/animal/dto/response/AnimalReadResults.java
  src/main/java/com/pet/domains/animal/service/AnimalKindService.java
  src/main/java/com/pet/domains/animal/service/AnimalService.java
  src/main/java/com/pet/domains/area/controller/CityController.java
  src/main/java/com/pet/domains/area/dto/response/CityReadResults.java
  src/main/java/com/pet/domains/area/service/CityService.java
  src/main/java/com/pet/domains/area/service/TownService.java
  src/main/resources/application.yml
Labels: feat, review needed

#325 [CP-324] fix: 디폴트 지역이 둘다 false인 경우 예외처리
  src/main/java/com/pet/domains/account/service/AccountService.java
Labels: bug

#327 [CP-326] feat: image 테이블 baseentity 상속 추가
  src/main/java/com/pet/domains/image/domain/Image.java
Labels: feat

#328 [CP-323] ec2 main으로 배포되도록 수정
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  deploy-dev.sh
  deploy-prod.sh
  src/main/resources/application-prod.yml
Labels: chore, review needed

#331 [CP-330] feat: profile prod 추가
  src/main/java/com/pet/infra/HtmlMailSender.java
Labels: bug

#333 [CP-332] 클라우드 와치 로그 전송
  build.gradle
  src/main/resources/logback.xml
Labels: feat, review needed

#338 [CP-336] oauth 문제 수정중
  src/main/java/com/pet/common/config/SecurityConfig.java
  src/main/java/com/pet/common/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java
Labels: bug

#340 [CP-339] fix: DB DATE 0 문제 수정
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: bug

#341 [CP-336] fix: oauth redirect url 수정
  src/main/java/com/pet/common/config/CookieUtil.java
  src/main/java/com/pet/common/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java
Labels: bug

#342 [CP-336] ouath 리다이렉트에 토큰값 전달
  src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java
Labels: feat

#334 [CP-307] feat: 모든 요청 Aop 로그 처리
  build.gradle
  src/main/java/com/pet/Application.java
  src/main/java/com/pet/common/aop/RequestLoggingAspect.java
  src/main/java/com/pet/common/config/InitDataConfig.java
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/post/service/ShelterApiService.java
Labels: feat

#344 [CP-343] 태그 엔티티 네임에 인덱스 추가
  src/main/java/com/pet/domains/tag/domain/Tag.java
Labels: feat, review needed

#346 [CP-345] 로그 스트림 포맷 변경
  src/main/resources/logback.xml
Labels: feat

#350 [CP-347] 슬랙 로그 알림 기능 및 프론트 요구사항 반영
  build.gradle
  src/main/java/com/pet/domains/account/dto/response/AccountBookmarkPostPageResults.java
  src/main/java/com/pet/domains/post/mapper/MissingPostMapper.java
  src/main/java/com/pet/domains/post/mapper/ShelterPostMapper.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
  src/test/java/com/pet/domains/account/controller/AccountControllerTest.java
Labels: feat

#352 [CP-350] 리다이렉트&슬랙 수정
  src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/logback.xml
Labels: 선 머지 후 리뷰!!

#351 [CP-348] feat: image validation 추가
  src/main/java/com/pet/common/config/RedisCachingConfig.java
  src/main/java/com/pet/common/config/RedisConfig.java
  src/main/java/com/pet/common/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/pet/common/s3/service/FileUploadService.java
  src/main/java/com/pet/common/s3/validator/ImageContentTypeValidator.java
  src/main/java/com/pet/common/s3/validator/ValidImage.java
  src/main/java/com/pet/infra/ConsoleEmailSender.java
  src/main/resources/application-rds.yml
Labels: feat, answer needed

#356 [CP-355] 쿠키로 조회수 중복으로 증가하지 않도록 수정
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
  src/main/java/com/pet/domains/post/domain/MissingPost.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/test/java/com/pet/domains/post/controller/MissingPostControllerTest.java
Labels: feat

#357 [CP-356] 쿠키 시큐어 설정
  src/main/java/com/pet/domains/post/controller/MissingPostController.java
Labels: feat

#360 [CP-259] Feature/359
  src/main/java/com/pet/common/exception/ExceptionHandlerAdvice.java
  src/main/java/com/pet/domains/account/domain/Provider.java
Labels: feat

#362 [CP-361] 북마크 게시글 이슈 수정
  src/main/java/com/pet/domains/post/repository/MissingPostCustomRepository.java
  src/main/java/com/pet/domains/post/repository/MissingPostCustomRepositoryImpl.java
  src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepository.java
  src/main/java/com/pet/domains/post/repository/ShelterPostCustomRepositoryImpl.java
  src/main/java/com/pet/domains/post/repository/projection/MissingPostWithFetch.java
  src/main/java/com/pet/domains/post/repository/projection/ShelterPostWithFetch.java
  src/main/java/com/pet/domains/post/service/MissingPostService.java
  src/main/java/com/pet/domains/post/service/ShelterPostService.java
  src/main/resources/logback.xml
  src/test/java/com/pet/domains/post/service/MissingPostServiceTest.java
Labels: bug

#364 [CP-363] fix: 게시물 수정시 품종 getOrCreate로 변경
  src/main/java/com/pet/domains/post/service/MissingPostService.java
Labels: bug

#366 [CP-365] 실종 게시글 날짜 필터링 이슈 수정
  src/main/java/com/pet/domains/post/repository/MissingPostCustomRepositoryImpl.java
Labels: bug
